[template]
description = 'Default Jarlet server template'
name = 'default'

[server]
memory = '2G'
minecraft_version = '26.2'
online_mode = true
port = 25565
package = 'paper'

[[plugins]]
id = 'WorldEdit'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'Geyser'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'ViaVersion'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'VaultUnlocked'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'plan-player-analytics/Plan'
source = 'github'

[plugins.policy]
pin = '5.8.3579'

[[plugins]]
id = 'EssentialsX/Essentials'
source = 'github'

[plugins.policy]
pin = '2.22.0'

[[plugins]]
id = 'ChestShop'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

# Additional popular Hangar plugins

[[plugins]]
id = 'ViaBackwards'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'BlueMap'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'GSit'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'Maintenance'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'SimpleVoiceChat'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'MiniMOTD'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'Multiverse-Core'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'PlaceholderAPI'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'

[[plugins]]
id = 'Skript'
source = 'hangar'

[plugins.policy]
channel = 'Release'
track = 'channel'