plugins {
    kotlin("jvm") version "2.4.10"
    kotlin("plugin.serialization") version "2.4.10"
    application
    id("org.graalvm.buildtools.native") version "1.1.8"
}

application {
    mainClass.set("me.devsnox.jarlet.MainKt")
}

graalvmNative {
    toolchainDetection.set(true)
    binaries {
        named("main") {
            imageName.set("jarlet")
            mainClass.set("me.devsnox.jarlet.MainKt")
            buildArgs.add("--no-fallback")
            javaLauncher.set(
                javaToolchains.launcherFor {
                    languageVersion.set(JavaLanguageVersion.of(25))
                }
            )
        }
    }
}

// Jarlet's own version lives in gradle.properties (jarletVersion*) -- the
// only source of truth. generateVersion below writes it into a single
// generated Kotlin constant (me.devsnox.jarlet.config.JarletVersion) instead
// of a bundled resource file that would need runtime parsing/validation:
// Gradle already knows these values are well-formed at build time, so
// there's nothing left to validate when the app reads them back.
version = run {
    val core = "${property("jarletVersionMajor")}.${property("jarletVersionMinor")}.${property("jarletVersionPatch")}"
    val stage = property("jarletVersionStage").toString()
    if (stage.equals("STABLE", ignoreCase = true)) core else "$core-${stage.lowercase()}.${property("jarletVersionRoll")}"
}

val generatedVersionDir = layout.buildDirectory.dir("generated/source/version/kotlin")

val generateVersion by tasks.registering {
    val outputDir = generatedVersionDir
    val versionValue = version.toString()
    outputs.dir(outputDir)

    doLast {
        val file = outputDir.get().file("me/devsnox/jarlet/config/JarletVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package me.devsnox.jarlet.config

            // Generated by app/build.gradle.kts's generateVersion task from
            // gradle.properties (jarletVersion*) -- do not edit directly.
            object JarletVersion {
                const val VERSION = "$versionValue"
            }
            """.trimIndent() + "\n"
        )
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.ORACLE)
    }
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.ORACLE)
    }
}

sourceSets {
    main {
        kotlin.srcDir(generateVersion.map { generatedVersionDir.get() })
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:5.1.0")
    implementation("com.github.ajalt.mordant:mordant:3.0.2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    implementation("org.tomlj:tomlj:1.1.1")
    implementation("org.snakeyaml:snakeyaml-engine:3.1.1")

    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}