# jarlet-sys.conf
PAPER_API=https://fill.papermc.io/v3
HANGAR_API=https://hangar.papermc.io/api/v1
SPIGET_API=https://api.spiget.org/v2
GITHUB_API=https://api.github.com
PROJECT_NAME=jarlet
REPO_URL=https://github.com/DevSnox/jarlet
SERVERS_DIR_DEFAULT=$HOME/jarlet/servers
TEMPLATE_FILENAME=jarlet.toml
STOP_TIMEOUT_SECONDS=60
STARTUP_CHECK_DELAY_SECONDS=2
PLUGIN_LIST_PAGE_SIZE=10
